### ISSUE TITLE
failed downloading this article

### ISSUE THREAD

**Issue by pomelo515** [caiotavares/spectrum-sensing#2]
I failed downloading this article in the website, would I ask for the full text for this article 'Machine learning-based models for spectrum sensing in cooperative radio networks'? Thank you very much!

**Comment by caiotavares** [comment]
Hi @pomelo515 , sure I can email the PDF for you. What's your email address?

**Comment by caiotavares** [comment]
You can also request the article directly from Research hate https://www.researchgate.net/publication/340002192_Machine_Learning-based_Models_for_Spectrum_Sensing_in_Cooperative_Radio_Networks
